# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: role.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "role.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nrole.proto\x12\x04role"6\n\x11\x43reateRoleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t"\x1c\n\x0eGetRoleRequest\x12\n\n\x02id\x18\x01 \x01(\t"B\n\x11UpdateRoleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t"(\n\x0cRoleResponse\x12\x18\n\x04role\x18\x01 \x01(\x0b\x32\n.role.Role"\x1f\n\x11\x44\x65leteRoleRequest\x12\n\n\x02id\x18\x01 \x01(\t"%\n\x12\x44\x65leteRoleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"3\n\x10ListRolesRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05"C\n\x11ListRolesResponse\x12\x19\n\x05roles\x18\x01 \x03(\x0b\x32\n.role.Role\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05"5\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2\xb7\x02\n\x0bRoleService\x12\x39\n\nCreateRole\x12\x17.role.CreateRoleRequest\x1a\x12.role.RoleResponse\x12\x33\n\x07GetRole\x12\x14.role.GetRoleRequest\x1a\x12.role.RoleResponse\x12\x39\n\nUpdateRole\x12\x17.role.UpdateRoleRequest\x1a\x12.role.RoleResponse\x12?\n\nDeleteRole\x12\x17.role.DeleteRoleRequest\x1a\x18.role.DeleteRoleResponse\x12<\n\tListRoles\x12\x16.role.ListRolesRequest\x1a\x17.role.ListRolesResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "role_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREATEROLEREQUEST"]._serialized_start = 20
    _globals["_CREATEROLEREQUEST"]._serialized_end = 74
    _globals["_GETROLEREQUEST"]._serialized_start = 76
    _globals["_GETROLEREQUEST"]._serialized_end = 104
    _globals["_UPDATEROLEREQUEST"]._serialized_start = 106
    _globals["_UPDATEROLEREQUEST"]._serialized_end = 172
    _globals["_ROLERESPONSE"]._serialized_start = 174
    _globals["_ROLERESPONSE"]._serialized_end = 214
    _globals["_DELETEROLEREQUEST"]._serialized_start = 216
    _globals["_DELETEROLEREQUEST"]._serialized_end = 247
    _globals["_DELETEROLERESPONSE"]._serialized_start = 249
    _globals["_DELETEROLERESPONSE"]._serialized_end = 286
    _globals["_LISTROLESREQUEST"]._serialized_start = 288
    _globals["_LISTROLESREQUEST"]._serialized_end = 339
    _globals["_LISTROLESRESPONSE"]._serialized_start = 341
    _globals["_LISTROLESRESPONSE"]._serialized_end = 408
    _globals["_ROLE"]._serialized_start = 410
    _globals["_ROLE"]._serialized_end = 463
    _globals["_ROLESERVICE"]._serialized_start = 466
    _globals["_ROLESERVICE"]._serialized_end = 777
# @@protoc_insertion_point(module_scope)
