# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/column.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "proto/column.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12proto/column.proto\x12\x06\x63olumn"5\n\x13\x43reateColumnRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x62oard_id\x18\x02 \x01(\t"\x1e\n\x10GetColumnRequest\x12\n\n\x02id\x18\x01 \x01(\t"A\n\x13UpdateColumnRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62oard_id\x18\x03 \x01(\t"0\n\x0e\x43olumnResponse\x12\x1e\n\x06\x63olumn\x18\x01 \x01(\x0b\x32\x0e.column.Column"!\n\x13\x44\x65leteColumnRequest\x12\n\n\x02id\x18\x01 \x01(\t"\'\n\x14\x44\x65leteColumnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"G\n\x12ListColumnsRequest\x12\x10\n\x08\x62oard_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05"K\n\x13ListColumnsResponse\x12\x1f\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x0e.column.Column\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05"4\n\x06\x43olumn\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62oard_id\x18\x03 \x01(\t2\xeb\x02\n\rColumnService\x12\x43\n\x0c\x43reateColumn\x12\x1b.column.CreateColumnRequest\x1a\x16.column.ColumnResponse\x12=\n\tGetColumn\x12\x18.column.GetColumnRequest\x1a\x16.column.ColumnResponse\x12\x43\n\x0cUpdateColumn\x12\x1b.column.UpdateColumnRequest\x1a\x16.column.ColumnResponse\x12I\n\x0c\x44\x65leteColumn\x12\x1b.column.DeleteColumnRequest\x1a\x1c.column.DeleteColumnResponse\x12\x46\n\x0bListColumns\x12\x1a.column.ListColumnsRequest\x1a\x1b.column.ListColumnsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.column_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREATECOLUMNREQUEST"]._serialized_start = 30
    _globals["_CREATECOLUMNREQUEST"]._serialized_end = 83
    _globals["_GETCOLUMNREQUEST"]._serialized_start = 85
    _globals["_GETCOLUMNREQUEST"]._serialized_end = 115
    _globals["_UPDATECOLUMNREQUEST"]._serialized_start = 117
    _globals["_UPDATECOLUMNREQUEST"]._serialized_end = 182
    _globals["_COLUMNRESPONSE"]._serialized_start = 184
    _globals["_COLUMNRESPONSE"]._serialized_end = 232
    _globals["_DELETECOLUMNREQUEST"]._serialized_start = 234
    _globals["_DELETECOLUMNREQUEST"]._serialized_end = 267
    _globals["_DELETECOLUMNRESPONSE"]._serialized_start = 269
    _globals["_DELETECOLUMNRESPONSE"]._serialized_end = 308
    _globals["_LISTCOLUMNSREQUEST"]._serialized_start = 310
    _globals["_LISTCOLUMNSREQUEST"]._serialized_end = 381
    _globals["_LISTCOLUMNSRESPONSE"]._serialized_start = 383
    _globals["_LISTCOLUMNSRESPONSE"]._serialized_end = 458
    _globals["_COLUMN"]._serialized_start = 460
    _globals["_COLUMN"]._serialized_end = 512
    _globals["_COLUMNSERVICE"]._serialized_start = 515
    _globals["_COLUMNSERVICE"]._serialized_end = 878
# @@protoc_insertion_point(module_scope)
